.lib tt_lib
.lib 'cmn018_assp_v1d2.l' tt
.lib 'cmn018_assp_v1d2.l' tt_3v
.lib 'cmn018_assp_v1d2.l' tt_m
.lib 'cmn018_assp_v1d2.l' tt_3m
.lib 'cmn018_assp_v1d2.l' tt_na
.lib 'cmn018_assp_v1d2.l' tt_3vna
.lib 'cmn018_assp_v1d2.l' tt_bip
.lib 'cmn018_assp_v1d2.l' tt_bip3
.lib 'cmn018_assp_v1d2.l' tt_dio3
.lib 'cmn018_assp_v1d2.l' tt_dio_m
.lib 'cmn018_assp_v1d2.l' tt_dio_3m
.lib 'cmn018_assp_v1d2.l' tt_dio_dnw
.lib 'cmn018_assp_v1d2.l' tt_res
.lib 'cmn018_assp_v1d2.l' tt_dio
.lib 'cmn018_assp_v1d2.l' tt_disres
.lib 'cmn018_assp_v1d2.l' tt_bbmvar
.lib 'cmn018_assp_v1d2.l' tt_mim
.lib 'cmn018_assp_v1d2.l' tt_rtmom
.lib 'cmn018_assp_v1d2.l' tt_fmom
.param mismatchflag_mos=0
.param mismatchflag_mos_3v=0
.param mismatchflag_mos_m=0
.param mismatchflag_mos_3m=0
.param mismatchflag_mos_na=0
.param mismatchflag_mos_3vna=0
.param mismatchflag_bip=0
.param mismatchflag_res=0
.param mismatchflag_disres=0
.param mismatchflag_mim=0
.param mismatchflag_rtmom=0
.param mismatchflag_fmom=0
.endl tt_lib

.lib ss_lib
.lib 'cmn018_assp_v1d2.l' ss
.lib 'cmn018_assp_v1d2.l' ss_3v
.lib 'cmn018_assp_v1d2.l' ss_m
.lib 'cmn018_assp_v1d2.l' ss_3m
.lib 'cmn018_assp_v1d2.l' ss_na
.lib 'cmn018_assp_v1d2.l' ss_3vna
.lib 'cmn018_assp_v1d2.l' ss_bip
.lib 'cmn018_assp_v1d2.l' ss_bip3
.lib 'cmn018_assp_v1d2.l' ss_dio3
.lib 'cmn018_assp_v1d2.l' ss_dio_m
.lib 'cmn018_assp_v1d2.l' ss_dio_3m
.lib 'cmn018_assp_v1d2.l' ss_dio_dnw
.lib 'cmn018_assp_v1d2.l' ss_res
.lib 'cmn018_assp_v1d2.l' ss_dio
.lib 'cmn018_assp_v1d2.l' ss_disres
.lib 'cmn018_assp_v1d2.l' ss_bbmvar
.lib 'cmn018_assp_v1d2.l' ss_mim
.lib 'cmn018_assp_v1d2.l' ss_rtmom
.lib 'cmn018_assp_v1d2.l' ss_fmom
.param mismatchflag_mos=0
.param mismatchflag_mos_3v=0
.param mismatchflag_mos_m=0
.param mismatchflag_mos_3m=0
.param mismatchflag_mos_na=0
.param mismatchflag_mos_3vna=0
.param mismatchflag_bip=0
.param mismatchflag_res=0
.param mismatchflag_disres=0
.param mismatchflag_mim=0
.param mismatchflag_rtmom=0
.param mismatchflag_fmom=0
.endl ss_lib

.lib ff_lib
.lib 'cmn018_assp_v1d2.l' ff
.lib 'cmn018_assp_v1d2.l' ff_3v
.lib 'cmn018_assp_v1d2.l' ff_m
.lib 'cmn018_assp_v1d2.l' ff_3m
.lib 'cmn018_assp_v1d2.l' ff_na
.lib 'cmn018_assp_v1d2.l' ff_3vna
.lib 'cmn018_assp_v1d2.l' ff_bip
.lib 'cmn018_assp_v1d2.l' ff_bip3
.lib 'cmn018_assp_v1d2.l' ff_dio3
.lib 'cmn018_assp_v1d2.l' ff_dio_m
.lib 'cmn018_assp_v1d2.l' ff_dio_3m
.lib 'cmn018_assp_v1d2.l' ff_dio_dnw
.lib 'cmn018_assp_v1d2.l' ff_res
.lib 'cmn018_assp_v1d2.l' ff_dio
.lib 'cmn018_assp_v1d2.l' ff_disres
.lib 'cmn018_assp_v1d2.l' ff_bbmvar
.lib 'cmn018_assp_v1d2.l' ff_mim
.lib 'cmn018_assp_v1d2.l' ff_rtmom
.lib 'cmn018_assp_v1d2.l' ff_fmom
.param mismatchflag_mos=0
.param mismatchflag_mos_3v=0
.param mismatchflag_mos_m=0
.param mismatchflag_mos_3m=0
.param mismatchflag_mos_na=0
.param mismatchflag_mos_3vna=0
.param mismatchflag_bip=0
.param mismatchflag_res=0
.param mismatchflag_disres=0
.param mismatchflag_mim=0
.param mismatchflag_rtmom=0
.param mismatchflag_fmom=0
.endl ff_lib

.lib sf_lib
.lib 'cmn018_assp_v1d2.l' sf
.lib 'cmn018_assp_v1d2.l' sf_3v
.lib 'cmn018_assp_v1d2.l' sf_m
.lib 'cmn018_assp_v1d2.l' sf_3m
.lib 'cmn018_assp_v1d2.l' sf_na
.lib 'cmn018_assp_v1d2.l' sf_3vna
.lib 'cmn018_assp_v1d2.l' tt_bip
.lib 'cmn018_assp_v1d2.l' tt_bip3
.lib 'cmn018_assp_v1d2.l' tt_dio3
.lib 'cmn018_assp_v1d2.l' tt_dio_m
.lib 'cmn018_assp_v1d2.l' tt_dio_3m
.lib 'cmn018_assp_v1d2.l' tt_dio_dnw
.lib 'cmn018_assp_v1d2.l' tt_res
.lib 'cmn018_assp_v1d2.l' tt_dio
.lib 'cmn018_assp_v1d2.l' tt_disres
.lib 'cmn018_assp_v1d2.l' tt_bbmvar
.lib 'cmn018_assp_v1d2.l' tt_mim
.lib 'cmn018_assp_v1d2.l' tt_rtmom
.lib 'cmn018_assp_v1d2.l' tt_fmom
.param mismatchflag_mos=0
.param mismatchflag_mos_3v=0
.param mismatchflag_mos_m=0
.param mismatchflag_mos_3m=0
.param mismatchflag_mos_na=0
.param mismatchflag_mos_3vna=0
.param mismatchflag_bip=0
.param mismatchflag_res=0
.param mismatchflag_disres=0
.param mismatchflag_mim=0
.param mismatchflag_rtmom=0
.param mismatchflag_fmom=0
.endl sf_lib

.lib fs_lib
.lib 'cmn018_assp_v1d2.l' fs
.lib 'cmn018_assp_v1d2.l' fs_3v
.lib 'cmn018_assp_v1d2.l' fs_m
.lib 'cmn018_assp_v1d2.l' fs_3m
.lib 'cmn018_assp_v1d2.l' fs_na
.lib 'cmn018_assp_v1d2.l' fs_3vna
.lib 'cmn018_assp_v1d2.l' tt_bip
.lib 'cmn018_assp_v1d2.l' tt_bip3
.lib 'cmn018_assp_v1d2.l' tt_dio3
.lib 'cmn018_assp_v1d2.l' tt_dio_m
.lib 'cmn018_assp_v1d2.l' tt_dio_3m
.lib 'cmn018_assp_v1d2.l' tt_dio_dnw
.lib 'cmn018_assp_v1d2.l' tt_res
.lib 'cmn018_assp_v1d2.l' tt_dio
.lib 'cmn018_assp_v1d2.l' tt_disres
.lib 'cmn018_assp_v1d2.l' tt_bbmvar
.lib 'cmn018_assp_v1d2.l' tt_mim
.lib 'cmn018_assp_v1d2.l' tt_rtmom
.lib 'cmn018_assp_v1d2.l' tt_fmom
.param mismatchflag_mos=0
.param mismatchflag_mos_3v=0
.param mismatchflag_mos_m=0
.param mismatchflag_mos_3m=0
.param mismatchflag_mos_na=0
.param mismatchflag_mos_3vna=0
.param mismatchflag_bip=0
.param mismatchflag_res=0
.param mismatchflag_disres=0
.param mismatchflag_mim=0
.param mismatchflag_rtmom=0
.param mismatchflag_fmom=0
.endl fs_lib

.lib mc_lib
.lib 'cmn018_assp_v1d2.l' mc
.lib 'cmn018_assp_v1d2.l' mc_3v
.lib 'cmn018_assp_v1d2.l' mc_m
.lib 'cmn018_assp_v1d2.l' mc_3m
.lib 'cmn018_assp_v1d2.l' mc_na
.lib 'cmn018_assp_v1d2.l' mc_3vna
.lib 'cmn018_assp_v1d2.l' mc_bip
.lib 'cmn018_assp_v1d2.l' tt_bip3
.lib 'cmn018_assp_v1d2.l' tt_dio3
.lib 'cmn018_assp_v1d2.l' tt_dio_m
.lib 'cmn018_assp_v1d2.l' tt_dio_3m
.lib 'cmn018_assp_v1d2.l' tt_dio_dnw
.lib 'cmn018_assp_v1d2.l' mc_res
.lib 'cmn018_assp_v1d2.l' tt_dio
.lib 'cmn018_assp_v1d2.l' mc_disres
.lib 'cmn018_assp_v1d2.l' mc_bbmvar
.lib 'cmn018_assp_v1d2.l' mc_mim
.lib 'cmn018_assp_v1d2.l' mc_rtmom
.lib 'cmn018_assp_v1d2.l' mc_fmom
.lib 'cmn018_assp_v1d2.l' stat
.lib 'cmn018_assp_v1d2.l' stat_res
.lib 'cmn018_assp_v1d2.l' stat_disres
.lib 'cmn018_assp_v1d2.l' stat_mim
.lib 'cmn018_assp_v1d2.l' stat_mom
.param mismatchflag_mos=0
.param mismatchflag_mos_3v=0
.param mismatchflag_mos_m=0
.param mismatchflag_mos_3m=0
.param mismatchflag_mos_na=0
.param mismatchflag_mos_3vna=0
.param mismatchflag_bip=0
.param mismatchflag_res=0
.param mismatchflag_disres=0
.param mismatchflag_mim=0
.param mismatchflag_rtmom=0
.param mismatchflag_fmom=0
.endl mc_lib

.lib mismatch_lib
.lib 'cmn018_assp_v1d2.l' tt
.lib 'cmn018_assp_v1d2.l' tt_3v
.lib 'cmn018_assp_v1d2.l' tt_m
.lib 'cmn018_assp_v1d2.l' tt_3m
.lib 'cmn018_assp_v1d2.l' tt_na
.lib 'cmn018_assp_v1d2.l' tt_3vna
.lib 'cmn018_assp_v1d2.l' tt_bip
.lib 'cmn018_assp_v1d2.l' tt_bip3
.lib 'cmn018_assp_v1d2.l' tt_dio3
.lib 'cmn018_assp_v1d2.l' tt_dio_m
.lib 'cmn018_assp_v1d2.l' tt_dio_3m
.lib 'cmn018_assp_v1d2.l' tt_dio_dnw
.lib 'cmn018_assp_v1d2.l' tt_res
.lib 'cmn018_assp_v1d2.l' tt_dio
.lib 'cmn018_assp_v1d2.l' tt_disres
.lib 'cmn018_assp_v1d2.l' tt_bbmvar
.lib 'cmn018_assp_v1d2.l' tt_mim
.lib 'cmn018_assp_v1d2.l' tt_rtmom
.lib 'cmn018_assp_v1d2.l' tt_fmom
.param mismatchflag_mos=1
.param mismatchflag_mos_3v=1
.param mismatchflag_mos_m=1
.param mismatchflag_mos_3m=1
.param mismatchflag_mos_na=1
.param mismatchflag_mos_3vna=1
.param mismatchflag_bip=1
.param mismatchflag_res=1
.param mismatchflag_disres=1
.param mismatchflag_mim=1
.param mismatchflag_rtmom=1
.param mismatchflag_fmom=1
.endl mismatch_lib

